Update 0-transfer_file

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -1,11 +1,21 @@
 #!/usr/bin/env bash
-# comment
-if [ $# -lt 4 ]; then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# Check if all 4 parameters are provided
+if [ $# -ne 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+PATH_TO_FILE="$1"
+IP="$2"
+USERNAME="$3"
+PATH_TO_SSH_KEY="$4"
+
+# Transfer the file using scp
+scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
+
+# Check the return code of scp and display success/failure message
+if [ $? -eq 0 ]; then
+    echo "File transfer successful!"
 else
-    file="$1"
-    host="$2"
-    username="$3"
-    private_key="$4"
-    scp -i "$private_key" -o StrictHostKeyChecking=no "$file" "$username@$host:~/"
+    echo "File transfer failed!"
 fi
